m1 = matrix(1:20, nrow=5, ncol=4)
print("5 × 4 matrix:")
print(m1)
cells = c(1:10)
m2 = matrix(cells, nrow=3, ncol=3, byrow=TRUE)
print("3 × 3 matrix with labels, filled by rows: ")
print(m2)
print("3 × 3 matrix with labels, filled by columns: ")
m3 = matrix(cells, nrow=2, ncol=2, byrow=FALSE)
print(m3)
